// AUTO-GENERATED by scripts/generate-icon-modules.mjs — DO NOT EDIT
import { registerIcon } from '../registry.ts';
registerIcon('git-commit', '<svg viewBox="0 0 256 256" fill="currentColor"><path d="M248,120H183.42a56,56,0,0,0-110.84,0H8a8,8,0,0,0,0,16H72.58a56,56,0,0,0,110.84,0H248a8,8,0,0,0,0-16ZM128,168a40,40,0,1,1,40-40A40,40,0,0,1,128,168Z"/></svg>');
