// AUTO-GENERATED by scripts/generate-icon-modules.mjs — DO NOT EDIT
import { registerIcon } from '../registry.ts';
registerIcon('paragraph-fill', '<svg viewBox="0 0 256 256" fill="currentColor"><path d="M216,48a8,8,0,0,1-8,8H192V208a8,8,0,0,1-16,0V56H152V208a8,8,0,0,1-16,0V168H96A64,64,0,0,1,96,40H208A8,8,0,0,1,216,48Z"/></svg>');
