// AUTO-GENERATED by scripts/generate-icon-modules.mjs — DO NOT EDIT
import { registerIcon } from '../registry.ts';
registerIcon('stop-circle-fill', '<svg viewBox="0 0 256 256" fill="currentColor"><path d="M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm32,132a4,4,0,0,1-4,4H100a4,4,0,0,1-4-4V100a4,4,0,0,1,4-4h56a4,4,0,0,1,4,4Z"/></svg>');
