// AUTO-GENERATED by scripts/generate-icon-modules.mjs — DO NOT EDIT
import { registerIcon } from '../registry.ts';
registerIcon('toggle-right-fill', '<svg viewBox="0 0 256 256" fill="currentColor"><path d="M176,56H80a72,72,0,0,0,0,144h96a72,72,0,0,0,0-144Zm0,112a40,40,0,1,1,40-40A40,40,0,0,1,176,168Z"/></svg>');
