// ── Controllers ──
export { DragController } from './drag/drag-controller.ts';
export type { DragOptions } from './drag/drag-controller.ts';
export { RangeSelectController } from './range-select/range-select-controller.ts';
export type { RangeSelectOptions } from './range-select/range-select-controller.ts';
export { ResizeController } from './resize/resize-controller.ts';
export type { ResizeOptions, HandlePosition } from './resize/resize-controller.ts';
export { VirtualScrollController } from './virtual-scroll/virtual-scroll-controller.ts';
export type { VirtualScrollOptions } from './virtual-scroll/virtual-scroll-controller.ts';
export { SelectionController } from './selection/selection-controller.ts';
export type { SelectionOptions } from './selection/selection-controller.ts';
export { SearchController } from './search/search-controller.ts';
export type { SearchOptions } from './search/search-controller.ts';
export { SwipeController } from './swipe/swipe-controller.ts';
export type { SwipeOptions, SwipeDirection } from './swipe/swipe-controller.ts';
export { EditController } from './edit/edit-controller.ts';
export type { EditOptions } from './edit/edit-controller.ts';
export { ClipboardController } from './clipboard/clipboard-controller.ts';
export type { ClipboardOptions } from './clipboard/clipboard-controller.ts';

// ── Standalone Controllers ──
export { PressController } from './press/press-controller.ts';
export type { PressOptions } from './press/press-controller.ts';
export { HoverController } from './hover/hover-controller.ts';
export type { HoverOptions } from './hover/hover-controller.ts';
export { CopyController } from './copy/copy-controller.ts';
export type { CopyOptions } from './copy/copy-controller.ts';
export { IntersectController } from './intersect/intersect-controller.ts';
export type { IntersectOptions } from './intersect/intersect-controller.ts';
export { DropZoneController } from './drop-zone/drop-zone-controller.ts';
export type { DropZoneOptions } from './drop-zone/drop-zone-controller.ts';
export { SortController } from './sort/sort-controller.ts';
export type { SortOptions, SortDirection } from './sort/sort-controller.ts';
export { ValidateController } from './validate/validate-controller.ts';
export type { ValidateOptions, ValidationRule } from './validate/validate-controller.ts';
export { FocusTrapController } from './focus-trap/focus-trap-controller.ts';
export { CollapsibleController } from './collapsible/collapsible-controller.ts';
export type { CollapsibleOptions } from './collapsible/collapsible-controller.ts';
export { RovingFocusController } from './roving-focus/roving-focus-controller.ts';
export type { RovingFocusOptions } from './roving-focus/roving-focus-controller.ts';
export { DismissController } from './dismiss/dismiss-controller.ts';
export { ModalController } from './modal/modal-controller.ts';
export type { ModalOptions } from './modal/modal-controller.ts';
export { ToastController } from './toast/toast-controller.ts';
export type { ToastOptions } from './toast/toast-controller.ts';
export { PopoverController } from './popover/popover-controller.ts';
export { ListNavigateController } from './list-navigate/list-navigate-controller.ts';
export type { ListNavigateOptions } from './list-navigate/list-navigate-controller.ts';
export { DialogController } from './dialog/dialog-controller.ts';
export type { DialogOptions } from './dialog/dialog-controller.ts';
export { GatewayController } from './gateway/gateway-controller.ts';
export type { GatewayOptions } from './gateway/gateway-controller.ts';
export { PresentController } from './present/present-controller.ts';
export type { PresentOptions } from './present/present-controller.ts';
export { TextTriggerController } from './text-trigger/text-trigger-controller.ts';
export type { TextTriggerItem, TextTriggerOptions, TextTriggerMatch } from './text-trigger/text-trigger-types.ts';
export { SlashCommandController } from './slash-command/slash-command-controller.ts';
export type { SlashCommand, SlashCommandOptions } from './slash-command/slash-command-controller.ts';
export { MentionController } from './mention/mention-controller.ts';
export type { MentionItem, MentionOptions } from './mention/mention-controller.ts';
export { BacktickWrapController } from './backtick-wrap/backtick-wrap-controller.ts';
export type { BacktickWrapOptions } from './backtick-wrap/backtick-wrap-controller.ts';
export { LinkPasteController } from './link-paste/link-paste-controller.ts';
export type { LinkPasteOptions } from './link-paste/link-paste-controller.ts';
export { ShortcutController } from './shortcut/shortcut-controller.ts';
export type { ShortcutBinding, ShortcutOptions } from './shortcut/shortcut-controller.ts';
export { TossController } from './toss/toss-controller.ts';
export type { TossOptions } from './toss/toss-controller.ts';
export { FlipController } from './flip/flip-controller.ts';
export type { FlipOptions } from './flip/flip-controller.ts';
export { ParallaxController } from './parallax/parallax-controller.ts';
export type { ParallaxOptions } from './parallax/parallax-controller.ts';
export { CSSInspectController } from './css-inspect/css-inspect-controller.ts';
export type { CSSInspectOptions } from './css-inspect/css-inspect-controller.ts';
export { ConfettiController } from './confetti/confetti-controller.ts';
export type { ConfettiOptions } from './confetti/confetti-controller.ts';
export { MagnetController } from './magnet/magnet-controller.ts';
export type { MagnetOptions } from './magnet/magnet-controller.ts';
export { NoodleController } from './noodle/noodle-controller.ts';
export type { NoodleOptions, NoodleConnection, PortSide } from './noodle/noodle-controller.ts';
export { isTypingContext } from './typing-context.ts';
export { registerAllTraits, registerCoreTraits, registerInteractionTraits, registerDevTraits } from './register-all.ts';

// ── Runtime ──
export { getTraitRuntime, DismissStack } from './runtime.ts';
export type { TraitRuntime, ToastOptions as RuntimeToastOptions } from './runtime.ts';
export { GestureRouter } from './gesture-router.ts';
export type { GestureParticipant } from './gesture-router.ts';

// ── Adapters (for selective registration via registerTrait()) ──
export { pressableAdapter } from './press/pressable-adapter.ts';
export { hoverableAdapter } from './hover/hoverable-adapter.ts';
export { copyableAdapter } from './copy/copyable-adapter.ts';
export { intersectableAdapter } from './intersect/intersectable-adapter.ts';
export { droppableAdapter } from './drop-zone/droppable-adapter.ts';
export { sortableAdapter } from './sort/sortable-adapter.ts';
export { validatableAdapter } from './validate/validatable-adapter.ts';
export { focusTrappableAdapter } from './focus-trap/focus-trappable-adapter.ts';
export { collapsibleAdapter } from './collapsible/collapsible-adapter.ts';
export { rovingFocusableAdapter } from './roving-focus/roving-focusable-adapter.ts';
export { dismissableAdapter } from './dismiss/dismissable-adapter.ts';
export { toastableAdapter } from './toast/toastable-adapter.ts';
export { popoverableAdapter } from './popover/popoverable-adapter.ts';
export { listNavigableAdapter } from './list-navigate/list-navigable-adapter.ts';
export { dialogableAdapter } from './dialog/dialogable-adapter.ts';
export { draggableAdapter } from './drag/draggable-adapter.ts';
export { rangeSelectableAdapter } from './range-select/range-selectable-adapter.ts';
export { resizableAdapter } from './resize/resizable-adapter.ts';
export { virtualizableAdapter } from './virtual-scroll/virtualizable-adapter.ts';
export { selectableAdapter } from './selection/selectable-adapter.ts';
export { searchableAdapter } from './search/searchable-adapter.ts';
export { clippableAdapter } from './clipboard/clippable-adapter.ts';
export { swipeableAdapter } from './swipe/swipeable-adapter.ts';
export { editableAdapter } from './edit/editable-adapter.ts';
export { presentableAdapter } from './present/presentable-adapter.ts';
export { slashCommandableAdapter } from './slash-command/slash-commandable-adapter.ts';
export { mentionableAdapter } from './mention/mentionable-adapter.ts';
export { backtickWrappableAdapter } from './backtick-wrap/backtick-wrappable-adapter.ts';
export { linkPasteableAdapter } from './link-paste/link-pasteable-adapter.ts';
export { shortcutableAdapter } from './shortcut/shortcutable-adapter.ts';
export { tossableAdapter } from './toss/tossable-adapter.ts';
export { flippableAdapter } from './flip/flippable-adapter.ts';
export { parallaxableAdapter } from './parallax/parallaxable-adapter.ts';
export { cssInspectableAdapter } from './css-inspect/css-inspectable-adapter.ts';
export { confettibleAdapter } from './confetti/confettible-adapter.ts';
export { magnetizableAdapter } from './magnet/magnetizable-adapter.ts';
export { noodleableAdapter } from './noodle/noodleable-adapter.ts';
export { gatewayableAdapter } from './gateway/gatewayable-adapter.ts';
export { modalableAdapter } from './modal/modalable-adapter.ts';
export { coreAdapters, interactionAdapters, devAdapters, allAdapters } from './adapters/index.ts';
