// generate-docs.mjs — Generates per-component/trait/controller .md files from YAML records.
// Usage: node scripts/generate-docs.mjs

import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from 'fs';
import { join, dirname, basename } from 'path';
import { fileURLToPath } from 'url';
import YAML from 'yaml';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const RECORDS_DIR = join(ROOT, 'records');

// ── File inventory ──

const FILE_PURPOSE = {
  'index.ts': 'Barrel exports',
  'README.md': 'Documentation (auto-generated)',
};

function inferFilePurpose(file, dirName) {
  if (FILE_PURPOSE[file]) return FILE_PURPOSE[file];
  if (file.endsWith('.test.ts')) return 'Tests';
  if (file.endsWith('.stories.ts')) return 'Storybook stories';
  if (file.endsWith('.html')) return 'Demo page';
  if (file.endsWith('.css')) return 'Styles';
  if (file.endsWith('-adapter.ts')) return 'Trait adapter (declarative provider bridge)';
  if (file.endsWith('-controller.ts')) return 'Controller (reactive state + behavior)';
  if (file.endsWith('-controller.md')) return 'Controller documentation';
  if (file.endsWith('-store.ts')) return 'Store (complex reactive state)';
  if (file.endsWith('-element.ts')) return 'Element class (behavior, no CSS)';
  if (file === `${dirName}.ts` || file === `n-${dirName}.ts`) return 'Custom element registration (define())';
  return 'Source module';
}

function extractFileInventory(dir) {
  if (!existsSync(dir)) return [];
  const dirName = basename(dir);
  const files = [];
  try {
    for (const entry of readdirSync(dir)) {
      const fullPath = join(dir, entry);
      const stat = statSync(fullPath);
      if (stat.isFile()) {
        files.push({ file: entry, purpose: inferFilePurpose(entry, dirName) });
      } else if (stat.isDirectory() && entry !== '__tests__' && entry !== 'node_modules') {
        const subFiles = readdirSync(fullPath).filter((f) => !f.startsWith('.'));
        files.push({ file: `${entry}/`, purpose: `Sub-directory (${subFiles.length} files)` });
      }
    }
  } catch { /* ignore */ }
  return files.sort((a, b) => a.file.localeCompare(b.file));
}

// ── Demo HTML extraction ──

function extractDemoSnippets(dir) {
  if (!existsSync(dir)) return [];
  const htmlFiles = readdirSync(dir).filter((f) => f.endsWith('.html'));
  if (htmlFiles.length === 0) return [];
  const snippets = [];
  for (const file of htmlFiles) {
    const html = readFileSync(join(dir, file), 'utf8');
    const re = /<pre\s+class="demo-code"><code>([\s\S]*?)<\/code><\/pre>/g;
    let m;
    while ((m = re.exec(html)) !== null) {
      const code = m[1]
        .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&')
        .replace(/&quot;/g, '"').replace(/&#39;/g, "'").trim();
      if (code.length > 10 && code.length < 1000) snippets.push(code);
    }
  }
  return [...new Set(snippets)].slice(0, 5);
}

function extractDemoUsageExamples(dir, tagName) {
  if (!existsSync(dir)) return [];
  const htmlFiles = readdirSync(dir).filter((f) => f.endsWith('.html'));
  if (htmlFiles.length === 0) return [];
  const examples = [];
  for (const file of htmlFiles) {
    const html = readFileSync(join(dir, file), 'utf8');
    const tagRe = new RegExp(`(<${tagName}[^>]*>[\\s\\S]*?<\\/${tagName}>)`, 'g');
    let m;
    let count = 0;
    while ((m = tagRe.exec(html)) !== null && count < 3) {
      const snippet = m[1].trim();
      if (snippet.length > 20 && snippet.length < 500 && snippet.includes(' ')) {
        examples.push(snippet);
        count++;
      }
    }
  }
  return examples.slice(0, 3);
}

// ── YAML helpers ──

function loadRecord(path) {
  return YAML.parse(readFileSync(path, 'utf8'));
}

function loadAllRecords(subdir) {
  const dir = join(RECORDS_DIR, subdir);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.yaml'))
    .map((f) => ({ file: f, name: basename(f, '.yaml'), record: loadRecord(join(dir, f)) }));
}

// ── Resolve source directory from record ──

function resolveDir(record) {
  const src = record.source;
  if (!src) return null;
  const first = src.element || src.css || src.controller || src.demo;
  if (!first) return null;
  return join(ROOT, dirname(first));
}

// ── Component README generation ──

function generateComponentReadme(record) {
  const lines = [`<!-- AUTO-GENERATED by scripts/generate-docs.mjs — DO NOT EDIT -->`, ``];

  // Title
  lines.push(`# ${record.tag}`, ``);
  if (record.description) lines.push(`> ${record.description}`, ``);

  // CSS-only badge
  if (record.css_only) {
    lines.push(`**CSS-only element** — styled purely via CSS, no JavaScript class required.`, ``);
  } else if (record.component) {
    lines.push(`**Class:** \`${record.component}\``, ``);
  }

  if (record.display) lines.push(`**Display:** \`${record.display}\``, ``);

  // Architecture summary
  const archNotes = [];
  if (record.a11y?.role) archNotes.push(`**ARIA role:** \`${record.a11y.role}\``);
  if (record.a11y?.form_associated) archNotes.push(`**Form-associated:** yes (participates in \`<form>\` submission, reset, validation)`);
  if (record.controllers?.length > 0) {
    archNotes.push(`**Internal controllers:** ${record.controllers.map((c) => `\`${c}\``).join(', ')}`);
  }
  if (archNotes.length > 0) lines.push(...archNotes, ``);

  // JS Attributes
  if (record.attributes && Object.keys(record.attributes).length > 0) {
    lines.push(`## Attributes`, ``);
    lines.push(`| Attribute | Type | Default | Description |`);
    lines.push(`|-----------|------|---------|-------------|`);
    for (const [name, attr] of Object.entries(record.attributes)) {
      const type = attr.type || 'string';
      const def = attr.default != null ? `\`${attr.default}\`` : '';
      const desc = attr.description || '';
      lines.push(`| \`${name}\` | \`${type}\` | ${def} | ${desc} |`);
    }
    lines.push(``);
  }

  // CSS Attributes
  if (record.css_attributes && Object.keys(record.css_attributes).length > 0) {
    lines.push(`## CSS Attributes`, ``);
    lines.push(`| Attribute | Type | Values | Description |`);
    lines.push(`|-----------|------|--------|-------------|`);
    for (const [name, attr] of Object.entries(record.css_attributes)) {
      const type = attr.type || 'string';
      const vals = attr.values?.map((v) => `\`${v}\``).join(', ') || (type === 'boolean' ? '_(boolean)_' : '');
      const desc = attr.description || '';
      lines.push(`| \`${name}\` | ${type} | ${vals} | ${desc} |`);
    }
    lines.push(``);
  }

  // Events
  if (record.events && Object.keys(record.events).length > 0) {
    lines.push(`## Events`, ``);
    lines.push(`| Event | Detail | Description |`);
    lines.push(`|-------|--------|-------------|`);
    for (const [name, evt] of Object.entries(record.events)) {
      const detail = evt.detail ? `\`{ ${Object.keys(evt.detail).join(', ')} }\`` : '_(none)_';
      const desc = evt.description || '';
      lines.push(`| \`${name}\` | ${detail} | ${desc} |`);
    }
    lines.push(``);
  }

  // Slots
  if (record.slots && Object.keys(record.slots).length > 0) {
    lines.push(`## Slots`, ``);
    lines.push(`| Slot | Description |`);
    lines.push(`|------|-------------|`);
    for (const [name, slot] of Object.entries(record.slots)) {
      lines.push(`| \`${name}\` | ${slot.description || ''} |`);
    }
    lines.push(``);
  }

  // CSS Custom Properties
  if (record.css_tokens && Object.keys(record.css_tokens).length > 0) {
    lines.push(`## CSS Custom Properties`, ``);
    lines.push(`| Token | Default | Purpose |`);
    lines.push(`|-------|---------|---------|`);
    for (const [name, token] of Object.entries(record.css_tokens)) {
      const def = token.default ? `\`${token.default}\`` : '';
      lines.push(`| \`${name}\` | ${def} | ${token.description || ''} |`);
    }
    lines.push(``);
  }

  // Accessibility
  if (record.a11y) {
    const a11y = record.a11y;
    const hasContent = a11y.role || a11y.form_associated || (a11y.keyboard?.length > 0) || (a11y.required_aria?.length > 0);
    if (hasContent) {
      lines.push(`## Accessibility`, ``);
      if (a11y.role) lines.push(`- **Role:** \`${a11y.role}\``);
      if (a11y.form_associated) lines.push(`- **Form-associated:** participates in form submission, reset, and validation`);
      if (a11y.required_aria?.length > 0) {
        for (const aria of a11y.required_aria) {
          lines.push(`- **Required ARIA:** \`${aria.attribute}\` ${aria.condition ? `(when ${aria.condition})` : ''}`);
        }
      }
      lines.push(``);
      if (a11y.keyboard?.length > 0) {
        lines.push(`### Keyboard`, ``);
        lines.push(`| Key | Action |`);
        lines.push(`|-----|--------|`);
        for (const k of a11y.keyboard) {
          lines.push(`| \`${k.key}\` | ${k.action || ''} |`);
        }
        lines.push(``);
      }
    }
  }

  // Behavior
  if (record.behavior?.length > 0) {
    lines.push(`## Behavior`, ``);
    for (const b of record.behavior) {
      const actions = Array.isArray(b.actions) ? b.actions.join(', ') : b.actions;
      lines.push(`- **${b.trigger}** → ${actions}`);
    }
    lines.push(``);
  }

  // Composition
  if (record.compose) {
    const { children, parents } = record.compose;
    if (children?.length > 0 || parents?.length > 0) {
      lines.push(`## Composition`, ``);
      if (children?.length > 0) {
        lines.push(`### Children`);
        for (const c of children) {
          const tag = typeof c === 'string' ? c : c.tag;
          const desc = typeof c === 'string' ? '' : (c.description || '');
          lines.push(`- \`<${tag}>\`${desc ? ` — ${desc}` : ''}`);
        }
        lines.push(``);
      }
      if (parents?.length > 0) {
        lines.push(`### Parents`);
        for (const p of parents) {
          const tag = typeof p === 'string' ? p : p.tag;
          const desc = typeof p === 'string' ? '' : (p.description || '');
          lines.push(`- \`<${tag}>\`${desc ? ` — ${desc}` : ''}`);
        }
        lines.push(``);
      }
    }
  }

  // Traits compatibility
  if (record.traits?.compatible?.length > 0) {
    lines.push(`## Compatible Traits`, ``);
    lines.push(record.traits.compatible.map((t) => `\`${t}\``).join(', '), ``);
  }

  // Usage
  lines.push(`## Usage`, ``);
  lines.push(`### Minimal`, ``);
  lines.push('```html');
  lines.push(`<${record.tag}></${record.tag}>`);
  lines.push('```', ``);

  // Demo examples
  const dir = resolveDir(record);
  if (dir) {
    const snippets = extractDemoSnippets(dir);
    if (snippets.length > 0) {
      lines.push(`### Examples from Demo`, ``);
      for (const snippet of snippets.slice(0, 3)) {
        lines.push('```html', snippet, '```', ``);
      }
    } else {
      const examples = extractDemoUsageExamples(dir, record.tag);
      if (examples.length > 0) {
        lines.push(`### Examples`, ``);
        for (const ex of examples.slice(0, 3)) {
          lines.push('```html', ex, '```', ``);
        }
      }
    }
  }

  // File inventory
  if (dir) {
    const files = extractFileInventory(dir);
    if (files.length > 0) {
      lines.push(`## File Inventory`, ``);
      lines.push(`| File | Purpose |`);
      lines.push(`|------|---------|`);
      for (const f of files) lines.push(`| \`${f.file}\` | ${f.purpose} |`);
      lines.push(``);
    }
  }

  return lines.join('\n');
}

// ── Trait README generation ──

function generateTraitReadme(record) {
  const lines = [`<!-- AUTO-GENERATED by scripts/generate-docs.mjs — DO NOT EDIT -->`, ``];

  lines.push(`# ${record.controller}`, ``);
  if (record.description) lines.push(`> ${record.description}`, ``);

  lines.push(`**Trait name:** \`${record.trait}\` (for use with \`<n-controller traits="${record.trait}">\` or self-trait \`traits="${record.trait}"\`)`, ``);

  // Constructor
  lines.push(`## Constructor`, ``);
  lines.push('```ts');
  const hasOptions = record.options && Object.keys(record.options).length > 0;
  const optionsType = `${record.controller.replace('Controller', '')}Options`;
  lines.push(`new ${record.controller}(host: HTMLElement${hasOptions ? `, options?: ${optionsType}` : ''})`);
  lines.push('```', ``);

  // Options
  if (hasOptions) {
    lines.push(`## Options`, ``);
    lines.push(`| Option | Type | Required | Description |`);
    lines.push(`|--------|------|----------|-------------|`);
    for (const [name, opt] of Object.entries(record.options)) {
      const required = opt.required ? 'yes' : 'no';
      lines.push(`| \`${name}\` | \`${opt.type}\` | ${required} | ${opt.description || ''} |`);
    }
    lines.push(``);
  }

  // Events
  if (record.injected_events && Object.keys(record.injected_events).length > 0) {
    lines.push(`## Events Dispatched`, ``);
    lines.push(`| Event | Detail |`);
    lines.push(`|-------|--------|`);
    for (const [name, evt] of Object.entries(record.injected_events)) {
      const detail = evt.detail ? `\`{ ${Object.keys(evt.detail).join(', ')} }\`` : '_(none)_';
      lines.push(`| \`${name}\` | ${detail} |`);
    }
    lines.push(``);
  }

  // Methods
  if (record.methods && Object.keys(record.methods).length > 0) {
    lines.push(`## Methods`, ``);
    lines.push(`| Method | Parameters | Returns |`);
    lines.push(`|--------|------------|---------|`);
    for (const [name, method] of Object.entries(record.methods)) {
      lines.push(`| \`${name}()\` | \`${method.params || '—'}\` | \`${method.returns}\` |`);
    }
    lines.push(``);
  }

  // Accessibility
  if (record.a11y?.keyboard?.length > 0) {
    lines.push(`## Accessibility`, ``);
    lines.push(`### Keyboard`, ``);
    lines.push(`| Key | Action |`);
    lines.push(`|-----|--------|`);
    for (const k of record.a11y.keyboard) {
      lines.push(`| \`${k.key}\` | ${k.action || ''} |`);
    }
    lines.push(``);
  }

  // Behavior
  if (record.behavior?.length > 0) {
    lines.push(`## Behavior`, ``);
    for (const b of record.behavior) {
      const actions = Array.isArray(b.actions) ? b.actions.join(', ') : b.actions;
      lines.push(`- **${b.trigger}** → ${actions}`);
    }
    lines.push(``);
  }

  // Consumption patterns
  lines.push(`## Consumption Patterns`, ``);
  lines.push(`### 1. Imperative (Controller)`, ``);
  lines.push('```ts');
  lines.push(`import { ${record.controller} } from '@nonoun/native-ui';`);
  lines.push(`const ctrl = new ${record.controller}(element${hasOptions ? ', { /* options */ }' : ''});`);
  lines.push(`// In teardown: ctrl.destroy();`);
  lines.push('```', ``);

  lines.push(`### 2. Declarative (Provider)`, ``);
  lines.push('```html');
  lines.push(`<n-controller traits="${record.trait}">`);
  lines.push(`  <div>Target element</div>`);
  lines.push(`</n-controller>`);
  lines.push('```', ``);

  lines.push(`### 3. Self-trait`, ``);
  lines.push('```html');
  lines.push(`<n-button traits="${record.trait}">Self-applying</n-button>`);
  lines.push('```', ``);

  // Trait option attributes
  if (hasOptions) {
    const firstOpt = Object.keys(record.options)[0];
    lines.push(`### Trait Option Attributes`, ``);
    lines.push(`When used as a provider or self-trait, options are passed via \`data-trait-${record.trait}-*\` attributes:`, ``);
    lines.push('```html');
    lines.push(`<n-controller traits="${record.trait}" data-trait-${record.trait}-${firstOpt}="value">`);
    lines.push(`  <div>Target</div>`);
    lines.push(`</n-controller>`);
    lines.push('```', ``);
  }

  // File inventory
  const dir = resolveDir(record);
  if (dir) {
    const files = extractFileInventory(dir);
    if (files.length > 0) {
      lines.push(`## File Inventory`, ``);
      lines.push(`| File | Purpose |`);
      lines.push(`|------|---------|`);
      for (const f of files) lines.push(`| \`${f.file}\` | ${f.purpose} |`);
      lines.push(``);
    }
  }

  return lines.join('\n');
}

// ── Controller README generation ──

function generateControllerReadme(record) {
  // Reuse trait format but without consumption patterns
  const lines = [`<!-- AUTO-GENERATED by scripts/generate-docs.mjs — DO NOT EDIT -->`, ``];

  lines.push(`# ${record.controller}`, ``);
  if (record.description) lines.push(`> ${record.description}`, ``);

  // Options
  if (record.options && Object.keys(record.options).length > 0) {
    lines.push(`## Options`, ``);
    lines.push(`| Option | Type | Description |`);
    lines.push(`|--------|------|-------------|`);
    for (const [name, opt] of Object.entries(record.options)) {
      lines.push(`| \`${name}\` | \`${opt.type}\` | ${opt.description || ''} |`);
    }
    lines.push(``);
  }

  // Events
  if (record.injected_events && Object.keys(record.injected_events).length > 0) {
    lines.push(`## Events Dispatched`, ``);
    lines.push(`| Event | Detail |`);
    lines.push(`|-------|--------|`);
    for (const [name, evt] of Object.entries(record.injected_events)) {
      const detail = evt.detail ? `\`{ ${Object.keys(evt.detail).join(', ')} }\`` : '_(none)_';
      lines.push(`| \`${name}\` | ${detail} |`);
    }
    lines.push(``);
  }

  // Methods
  if (record.methods && Object.keys(record.methods).length > 0) {
    lines.push(`## Methods`, ``);
    lines.push(`| Method | Returns |`);
    lines.push(`|--------|---------|`);
    for (const [name, method] of Object.entries(record.methods)) {
      lines.push(`| \`${name}()\` | \`${method.returns}\` |`);
    }
    lines.push(``);
  }

  // File inventory
  const dir = resolveDir(record);
  if (dir) {
    const files = extractFileInventory(dir);
    if (files.length > 0) {
      lines.push(`## File Inventory`, ``);
      lines.push(`| File | Purpose |`);
      lines.push(`|------|---------|`);
      for (const f of files) lines.push(`| \`${f.file}\` | ${f.purpose} |`);
      lines.push(``);
    }
  }

  return lines.join('\n');
}

// ── Group records by source directory ──

function groupByDir(records) {
  const groups = new Map();
  for (const { record, name } of records) {
    const dir = resolveDir(record);
    if (!dir) continue;
    if (!groups.has(dir)) groups.set(dir, []);
    groups.get(dir).push({ record, name });
  }
  return groups;
}

// ── Main ──

function main() {
  let componentCount = 0;
  let traitCount = 0;
  let controllerCount = 0;

  // 1. Load all records
  const componentRecords = loadAllRecords('components');
  const containerRecords = loadAllRecords('containers');
  const traitRecords = loadAllRecords('traits');
  const controllerRecords = loadAllRecords('controllers');

  // 2. Group component/container records by source directory
  const allCompRecords = [...componentRecords, ...containerRecords];
  const dirGroups = groupByDir(allCompRecords);

  // 3. Generate one README per source directory
  for (const [dir, entries] of dirGroups) {
    // If single record in dir, just generate its README
    // If multiple records, generate combined README with primary first
    const lines = [];

    // Sort: primary element first (tag matches dir name or is shortest)
    const dirName = basename(dir);
    entries.sort((a, b) => {
      const aMatch = a.record.tag === `n-${dirName}`;
      const bMatch = b.record.tag === `n-${dirName}`;
      if (aMatch && !bMatch) return -1;
      if (!aMatch && bMatch) return 1;
      return a.record.tag.length - b.record.tag.length;
    });

    if (entries.length === 1) {
      const md = generateComponentReadme(entries[0].record);
      writeFileSync(join(dir, 'README.md'), md);
      componentCount++;
    } else {
      // Combined README for multi-element directories
      const primary = entries[0];
      lines.push(generateComponentReadme(primary.record));

      for (let i = 1; i < entries.length; i++) {
        lines.push(`---`, ``);
        // Generate secondary element section (reduced heading level)
        const secMd = generateComponentReadme(entries[i].record);
        // Replace top-level headings with sub-headings
        const adjusted = secMd
          .replace('<!-- AUTO-GENERATED by scripts/generate-docs.mjs — DO NOT EDIT -->\n\n', '')
          .replace(/^# /gm, '## ')
          .replace(/^## ## /gm, '### ');
        lines.push(adjusted);
      }
      writeFileSync(join(dir, 'README.md'), lines.join('\n'));
      componentCount += entries.length;
    }
  }

  // 4. Handle directories without records (CSS-only from shared files)
  const SRC_DIRS = [join(ROOT, 'src/components'), join(ROOT, 'src/containers')];
  for (const srcDir of SRC_DIRS) {
    if (!existsSync(srcDir)) continue;
    for (const name of readdirSync(srcDir)) {
      const dir = join(srcDir, name);
      if (!statSync(dir).isDirectory()) continue;
      if (name === '__tests__') continue;
      if (existsSync(join(dir, 'README.md'))) continue; // Already handled

      const dirFiles = readdirSync(dir);
      if (dirFiles.length === 0) continue;

      const lines = [`<!-- AUTO-GENERATED by scripts/generate-docs.mjs — DO NOT EDIT -->`, ``, `# n-${name}`, ``];
      lines.push(`**CSS-only element** — styled via shared CSS files (layout.css, containers.css, or content.css).`, ``);

      const files = extractFileInventory(dir);
      if (files.length > 0) {
        lines.push(`## File Inventory`, ``);
        lines.push(`| File | Purpose |`);
        lines.push(`|------|---------|`);
        for (const f of files) lines.push(`| \`${f.file}\` | ${f.purpose} |`);
        lines.push(``);
      }
      lines.push(`## Usage`, ``);
      lines.push('```html');
      lines.push(`<n-${name}></n-${name}>`);
      lines.push('```', ``);
      writeFileSync(join(dir, 'README.md'), lines.join('\n'));
      componentCount++;
    }
  }

  // 5. Generate trait docs
  for (const { record } of traitRecords) {
    const dir = resolveDir(record);
    if (!dir) continue;
    const md = generateTraitReadme(record);
    const outName = basename(record.source.controller).replace('.ts', '.md');
    writeFileSync(join(dir, outName), md);
    traitCount++;
  }

  // 6. Generate standalone controller docs
  for (const { record } of controllerRecords) {
    const dir = resolveDir(record);
    if (!dir) continue;

    // Check for hand-written docs
    const existingMd = readdirSync(dir).find((f) => f.endsWith('.md'));
    if (existingMd) {
      const content = readFileSync(join(dir, existingMd), 'utf8');
      if (!content.includes('AUTO-GENERATED')) continue;
    }

    const md = generateControllerReadme(record);
    const outName = basename(record.source.controller).replace('.ts', '.md');
    writeFileSync(join(dir, outName), md);
    controllerCount++;
  }

  console.log(`Docs generated from YAML records: ${componentCount} components/containers, ${traitCount} traits, ${controllerCount} controllers`);
}

main();
