// AUTO-GENERATED docs script — reads CEM + source files to produce per-component/controller .md files.
// Usage: node scripts/generate-docs.mjs

import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'fs';
import { join, dirname, basename, relative } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const CEM_PATH = join(ROOT, 'dist/custom-elements.json');
const TRAITS_DIR = join(ROOT, 'src/traits');

// ── CEM parsing ──

function loadCEM() {
  const raw = readFileSync(CEM_PATH, 'utf8');
  return JSON.parse(raw);
}

function extractSlots(cssPath) {
  if (!existsSync(cssPath)) return [];
  const css = readFileSync(cssPath, 'utf8');
  const slots = new Set();
  // Match [slot="name"] patterns in CSS
  const re = /\[slot=["']([^"']+)["']\]/g;
  let m;
  while ((m = re.exec(css)) !== null) {
    slots.add(m[1]);
  }
  return [...slots].sort();
}

// ── Controller parsing ──

function parseController(filePath) {
  if (!existsSync(filePath)) return null;
  const src = readFileSync(filePath, 'utf8');

  // Extract class JSDoc
  const classDocMatch = src.match(/\/\*\*\s*([^*](?:[^*]|\*(?!\/))*?)\*\/\s*export class (\w+)/);
  const description = classDocMatch ? classDocMatch[1].replace(/\s*\*\s*/g, ' ').trim() : '';
  const className = classDocMatch ? classDocMatch[2] : basename(filePath, '.ts').replace(/-(\w)/g, (_, c) => c.toUpperCase()).replace(/^\w/, c => c.toUpperCase());

  // Extract options interface
  const optionsMatch = src.match(/export interface (\w+Options)\s*\{([^}]+)\}/s);
  const optionsName = optionsMatch ? optionsMatch[1] : null;
  const optionsFields = [];
  if (optionsMatch) {
    const body = optionsMatch[2];
    // Match: fieldName?: Type; or fieldName: Type; with optional JSDoc
    const fieldRe = /(?:\/\*\*\s*(.*?)\s*\*\/\s*)?(\w+)(\?)?:\s*([^;]+);/g;
    let fm;
    while ((fm = fieldRe.exec(body)) !== null) {
      optionsFields.push({
        name: fm[2],
        optional: !!fm[3],
        type: fm[4].trim(),
        description: fm[1] ? fm[1].replace(/\s*\*\s*/g, ' ').trim() : '',
      });
    }
  }

  // Extract events dispatched (new CustomEvent('event-name', ...))
  const events = [];
  const eventRe = /new CustomEvent\(['"]([^'"]+)['"]\s*,\s*\{[^}]*detail:\s*\{([^}]*)\}/g;
  let em;
  while ((em = eventRe.exec(src)) !== null) {
    // Clean detail: extract field names only (strip this.#, variable refs, trailing commas)
    const raw = em[2].replace(/\s+/g, ' ').trim();
    const fields = raw
      .split(',')
      .map(f => f.trim())
      .filter(Boolean)
      .map(f => {
        const [key] = f.split(':').map(s => s.trim());
        return key;
      })
      .join(', ');
    events.push({ name: em[1], detail: fields });
  }
  // Deduplicate by name
  const uniqueEvents = [...new Map(events.map(e => [e.name, e])).values()];

  // Extract public methods (not starting with #, not constructor)
  const SKIP_METHODS = new Set(['constructor', 'attach', 'detach', 'if', 'for', 'while', 'switch', 'return', 'const', 'let', 'var', 'new', 'else', 'try', 'catch']);
  const methods = [];
  const methodRe = /^\s+(?:readonly\s+)?(\w+)\s*\([^)]*\)\s*(?::\s*\S+)?\s*\{/gm;
  let mm;
  while ((mm = methodRe.exec(src)) !== null) {
    const name = mm[1];
    if (name.startsWith('#') || SKIP_METHODS.has(name)) continue;
    if (!methods.includes(name)) methods.push(name);
  }
  // Also check arrow function properties that are public
  const arrowRe = /^\s+readonly\s+(\w+)\s*=/gm;
  let am;
  while ((am = arrowRe.exec(src)) !== null) {
    if (!am[1].startsWith('#') && !methods.includes(am[1])) methods.push(am[1]);
  }
  // Always include destroy if present
  if (src.includes('destroy()') && !methods.includes('destroy')) methods.push('destroy');

  return { className, description, optionsName, optionsFields, events: uniqueEvents, methods };
}

// ── Markdown generation ──

function generateComponentMd(tagName, cls, attrs, events, slots, cssPath) {
  const lines = [`<!-- AUTO-GENERATED by scripts/generate-docs.mjs — DO NOT EDIT -->`, ``, `# ${tagName}`, ``];

  if (cls.description) {
    lines.push(`> ${cls.description}`, ``);
  }

  lines.push(`**Class:** \`${cls.name}\``, ``);

  // Attributes
  if (attrs.length > 0) {
    lines.push(`## Attributes`, ``);
    lines.push(`| Attribute | Type | Description |`);
    lines.push(`|-----------|------|-------------|`);
    for (const attr of attrs) {
      const type = attr.type?.text || 'string';
      const desc = attr.description || '';
      lines.push(`| \`${attr.name}\` | \`${type}\` | ${desc} |`);
    }
    lines.push(``);
  }

  // Events
  if (events.length > 0) {
    lines.push(`## Events`, ``);
    lines.push(`| Event | Description |`);
    lines.push(`|-------|-------------|`);
    for (const event of events) {
      lines.push(`| \`${event.name}\` | ${event.description || ''} |`);
    }
    lines.push(``);
  }

  // Slots
  if (slots.length > 0) {
    lines.push(`## Slots`, ``);
    lines.push(`| Slot | |`);
    lines.push(`|------|-|`);
    for (const slot of slots) {
      lines.push(`| \`${slot}\` | |`);
    }
    lines.push(``);
  }

  // Usage
  lines.push(`## Usage`, ``);
  lines.push('```html');
  lines.push(`<${tagName}></${tagName}>`);
  lines.push('```');
  lines.push(``);

  return lines.join('\n');
}

function generateControllerMd(info) {
  const lines = [`<!-- AUTO-GENERATED by scripts/generate-docs.mjs — DO NOT EDIT -->`, ``, `# ${info.className}`, ``];

  if (info.description) {
    lines.push(`> ${info.description}`, ``);
  }

  // Constructor
  if (info.optionsName) {
    lines.push(`## Constructor`, ``);
    lines.push('```ts');
    lines.push(`new ${info.className}(host: HTMLElement, options?: ${info.optionsName})`);
    lines.push('```');
    lines.push(``);
  }

  // Options
  if (info.optionsFields.length > 0) {
    lines.push(`## Options`, ``);
    lines.push(`| Option | Type | Required | Description |`);
    lines.push(`|--------|------|----------|-------------|`);
    for (const f of info.optionsFields) {
      lines.push(`| \`${f.name}\` | \`${f.type}\` | ${f.optional ? 'no' : 'yes'} | ${f.description} |`);
    }
    lines.push(``);
  }

  // Events
  if (info.events.length > 0) {
    lines.push(`## Events Dispatched`, ``);
    lines.push(`| Event | Detail |`);
    lines.push(`|-------|--------|`);
    for (const e of info.events) {
      lines.push(`| \`${e.name}\` | \`{ ${e.detail} }\` |`);
    }
    lines.push(``);
  }

  // Methods
  if (info.methods.length > 0) {
    lines.push(`## Methods`, ``);
    lines.push(`| Method |`);
    lines.push(`|--------|`);
    for (const m of info.methods) {
      lines.push(`| \`${m}()\` |`);
    }
    lines.push(``);
  }

  // Usage
  lines.push(`## Usage`, ``);
  lines.push('```ts');
  lines.push(`import { ${info.className} } from '@nonoun/native-ui';`);
  if (info.optionsName) {
    lines.push(`const ctrl = new ${info.className}(element, { /* options */ });`);
  } else {
    lines.push(`const ctrl = new ${info.className}(element);`);
  }
  lines.push(`// In teardown: ctrl.destroy();`);
  lines.push('```');
  lines.push(``);

  return lines.join('\n');
}

// ── Main ──

function main() {
  const cem = loadCEM();
  let componentCount = 0;
  let controllerCount = 0;

  // 1. Generate component docs
  for (const mod of cem.modules) {
    for (const decl of mod.declarations || []) {
      if (!decl.tagName) continue;

      const srcPath = join(ROOT, mod.path);
      const dir = dirname(srcPath);
      const tagName = decl.tagName;

      // Find CSS file
      const cssFile = join(dir, `${tagName}.css`);
      // Also check parent dir for sub-elements (e.g. ui-accordion-item lives in ui-accordion/)
      const parentCssFile = join(dirname(dir), `${dirname(mod.path).split('/').pop()}.css`);
      const cssPath = existsSync(cssFile) ? cssFile : existsSync(parentCssFile) ? parentCssFile : null;

      const slots = cssPath ? extractSlots(cssPath) : [];
      const attrs = decl.attributes || [];
      const events = decl.events || [];

      const md = generateComponentMd(tagName, decl, attrs, events, slots, cssPath);
      const outPath = join(dir, 'README.md');
      writeFileSync(outPath, md);
      componentCount++;
    }
  }

  // 2. Generate controller docs
  const docsDir = join(TRAITS_DIR, 'docs');
  if (!existsSync(docsDir)) mkdirSync(docsDir, { recursive: true });

  const controllerFiles = readdirSync(TRAITS_DIR)
    .filter(f => f.endsWith('-controller.ts') && !f.endsWith('.test.ts'));

  for (const file of controllerFiles) {
    const filePath = join(TRAITS_DIR, file);
    const info = parseController(filePath);
    if (!info) continue;

    const md = generateControllerMd(info);
    const outName = file.replace('.ts', '.md');
    writeFileSync(join(docsDir, outName), md);
    controllerCount++;
  }

  // 3. Also generate docs for container elements from CEM
  // (containers with element classes appear in CEM too)

  console.log(`Docs generated: ${componentCount} components, ${controllerCount} controllers`);
}

main();
