// ── Controllers ──
export { DragController } from './drag-controller.ts';
export type { DragOptions } from './drag-controller.ts';
export { RangeSelectController } from './range-select-controller.ts';
export type { RangeSelectOptions } from './range-select-controller.ts';
export { ResizeController } from './resize-controller.ts';
export type { ResizeOptions, HandlePosition } from './resize-controller.ts';
export { VirtualScrollController } from './virtual-scroll-controller.ts';
export type { VirtualScrollOptions } from './virtual-scroll-controller.ts';
export { SelectionController } from './selection-controller.ts';
export type { SelectionOptions } from './selection-controller.ts';
export { SearchController } from './search-controller.ts';
export type { SearchOptions } from './search-controller.ts';
export { SwipeController } from './swipe-controller.ts';
export type { SwipeOptions, SwipeDirection } from './swipe-controller.ts';
export { EditController } from './edit-controller.ts';
export type { EditOptions } from './edit-controller.ts';
export { ClipboardController } from './clipboard-controller.ts';
export type { ClipboardOptions } from './clipboard-controller.ts';

// ── Standalone Controllers ──
export { PressController } from './press-controller.ts';
export type { PressOptions } from './press-controller.ts';
export { HoverController } from './hover-controller.ts';
export type { HoverOptions } from './hover-controller.ts';
export { CopyController } from './copy-controller.ts';
export type { CopyOptions } from './copy-controller.ts';
export { IntersectController } from './intersect-controller.ts';
export type { IntersectOptions } from './intersect-controller.ts';
export { DropZoneController } from './drop-zone-controller.ts';
export type { DropZoneOptions } from './drop-zone-controller.ts';
export { SortController } from './sort-controller.ts';
export type { SortOptions, SortDirection } from './sort-controller.ts';
export { ValidateController } from './validate-controller.ts';
export type { ValidateOptions, ValidationRule } from './validate-controller.ts';
export { FocusTrapController } from './focus-trap-controller.ts';
export { CollapsibleController } from './collapsible-controller.ts';
export type { CollapsibleOptions } from './collapsible-controller.ts';
export { RovingFocusController } from './roving-focus-controller.ts';
export type { RovingFocusOptions } from './roving-focus-controller.ts';
export { DismissController } from './dismiss-controller.ts';
export { ToastController } from './toast-controller.ts';
export type { ToastOptions } from './toast-controller.ts';
export { PopoverController } from './popover-controller.ts';
export { ListNavigateController } from './list-navigate-controller.ts';
export type { ListNavigateOptions } from './list-navigate-controller.ts';
export { DialogController } from './dialog-controller.ts';
export type { DialogOptions } from './dialog-controller.ts';
export { GatewayController } from './gateway-controller.ts';
export type { GatewayOptions } from './gateway-controller.ts';
export { PresentController } from './present-controller.ts';
export type { PresentOptions } from './present-controller.ts';
export { SlashCommandController } from './slash-command-controller.ts';
export type { SlashCommand, SlashCommandOptions } from './slash-command-controller.ts';
export { ShortcutController } from './shortcut-controller.ts';
export type { ShortcutBinding, ShortcutOptions } from './shortcut-controller.ts';
export { TossController } from './toss-controller.ts';
export type { TossOptions } from './toss-controller.ts';
export { CSSInspectController } from './css-inspect-controller.ts';
export type { CSSInspectOptions } from './css-inspect-controller.ts';
export { isTypingContext } from './typing-context.ts';
export { registerAllTraits } from './register-all.ts';

// ── Runtime ──
export { getTraitRuntime, DismissStack } from './runtime.ts';
export type { TraitRuntime, ToastOptions as RuntimeToastOptions } from './runtime.ts';
export { GestureRouter } from './gesture-router.ts';
export type { GestureParticipant } from './gesture-router.ts';

// ── Adapters (for selective registration via registerTrait()) ──
export { pressableAdapter } from './adapters/pressable-adapter.ts';
export { hoverableAdapter } from './adapters/hoverable-adapter.ts';
export { copyableAdapter } from './adapters/copyable-adapter.ts';
export { intersectableAdapter } from './adapters/intersectable-adapter.ts';
export { droppableAdapter } from './adapters/droppable-adapter.ts';
export { sortableAdapter } from './adapters/sortable-adapter.ts';
export { validatableAdapter } from './adapters/validatable-adapter.ts';
export { focusTrappableAdapter } from './adapters/focus-trappable-adapter.ts';
export { collapsibleAdapter } from './adapters/collapsible-adapter.ts';
export { rovingFocusableAdapter } from './adapters/roving-focusable-adapter.ts';
export { dismissableAdapter } from './adapters/dismissable-adapter.ts';
export { toastableAdapter } from './adapters/toastable-adapter.ts';
export { popoverableAdapter } from './adapters/popoverable-adapter.ts';
export { listNavigableAdapter } from './adapters/list-navigable-adapter.ts';
export { dialogableAdapter } from './adapters/dialogable-adapter.ts';
export { draggableAdapter } from './adapters/draggable-adapter.ts';
export { rangeSelectableAdapter } from './adapters/range-selectable-adapter.ts';
export { resizableAdapter } from './adapters/resizable-adapter.ts';
export { virtualizableAdapter } from './adapters/virtualizable-adapter.ts';
export { selectableAdapter } from './adapters/selectable-adapter.ts';
export { searchableAdapter } from './adapters/searchable-adapter.ts';
export { clippableAdapter } from './adapters/clippable-adapter.ts';
export { swipeableAdapter } from './adapters/swipeable-adapter.ts';
export { editableAdapter } from './adapters/editable-adapter.ts';
export { presentableAdapter } from './adapters/presentable-adapter.ts';
export { slashCommandableAdapter } from './adapters/slash-commandable-adapter.ts';
export { shortcutableAdapter } from './adapters/shortcutable-adapter.ts';
export { tossableAdapter } from './adapters/tossable-adapter.ts';
export { cssInspectableAdapter } from './adapters/css-inspectable-adapter.ts';
